language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_cdbfd4aee24b_key -iv $encrypted_cdbfd4aee24b_iv -in application.properties.enc -out src/main/resources/application.properties -d
